# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_applicationuser_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('first_name', models.CharField(max_length=50, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phoneNumber', models.CharField(unique=True, max_length=17, verbose_name='Phone Number')),
                ('Martial_status', models.CharField(max_length=1, null=True, verbose_name='Martial Status', choices=[(b'M', b'Married'), (b'S', b'Single')])),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('home_address1', models.CharField(max_length=1000, verbose_name='Home Address1')),
                ('home_address2', models.CharField(max_length=1000, verbose_name='Home Address2')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('postCode', models.IntegerField(max_length=5, verbose_name=b'Post code / Zip code')),
                ('form_date', models.DateField(max_length=100, verbose_name='Form Date')),
                ('dateOFBirth', models.DateField(max_length=100, verbose_name='Date OF Birth')),
                ('socialSecurityNumber', models.CharField(max_length=70, verbose_name='Martial Status')),
                ('no_year_experience', models.IntegerField(max_length=20, null=True, verbose_name='Years Of Experience', blank=True)),
                ('no_of_dependents', models.IntegerField(max_length=20, null=True, verbose_name='Number Of Dependents', blank=True)),
                ('emergency_contact_firstName', models.CharField(max_length=500, verbose_name='Emergency Contact FirstName')),
                ('emergency_contact_lastName', models.CharField(max_length=500, verbose_name='Emergency Contact LastName')),
                ('emergency_contact_phoneNumber', models.CharField(max_length=17, verbose_name='Emergency Contact PhoneNumber')),
                ('emergency_contact_relation', models.CharField(max_length=17, verbose_name='Emergency Contact Relation')),
                ('ceiling_mechanic', models.BooleanField(default=False, verbose_name='Ceiling Mechanic')),
                ('framing_mechanic', models.BooleanField(default=False, verbose_name='Framing Mechanic')),
                ('drywall_hanger', models.BooleanField(default=False, verbose_name='DryWall Hanger')),
                ('drywall_finisher', models.BooleanField(default=False, verbose_name='DryWall Finisher')),
                ('general_larborer', models.BooleanField(default=False, verbose_name='General Larborer')),
                ('painter_tradesman', models.BooleanField(default=False, verbose_name='Painter Tradesman')),
                ('plaster_tradesman', models.BooleanField(default=False, verbose_name='Plaster Tradesman')),
                ('masonry_bricklayer', models.BooleanField(default=False, verbose_name='Masonry BrickLayer')),
                ('masonry_blocklayer', models.BooleanField(default=False, verbose_name='Masonry BlockLayer')),
                ('carpenter', models.BooleanField(default=False, verbose_name='Carpenter')),
                ('concrete_forming', models.BooleanField(default=False, verbose_name='Concrete Forming')),
                ('concrete_finisher', models.BooleanField(default=False, verbose_name='Concrete Finisher')),
                ('osha_manager', models.BooleanField(default=False, verbose_name='Osha Manager')),
                ('project_manager', models.BooleanField(default=False, verbose_name='Project Manager')),
                ('is_ladder_user', models.BooleanField(default=False)),
                ('is_wheelbrrow_user', models.BooleanField(default=False)),
                ('is_general_hand_tools', models.BooleanField(default=False)),
                ('is_walking_slits', models.BooleanField(default=False)),
                ('is_electric_screw_gun', models.BooleanField(default=False)),
                ('is_electric_chop_saw', models.BooleanField(default=False)),
                ('is_power_nail_gun', models.BooleanField(default=False)),
                ('is_wallboard_hoist', models.BooleanField(default=False)),
                ('is_scissor_lift', models.BooleanField(default=False)),
                ('is_boom_lift', models.BooleanField(default=False)),
                ('is_bucket_truck_lift', models.BooleanField(default=False)),
                ('is_new_skill', models.BooleanField(default=False)),
                ('is_osha10', models.BooleanField(default=False)),
                ('is_osha30', models.BooleanField(default=False)),
                ('is_osha_training_manager', models.BooleanField(default=False)),
                ('is_power_tool_certified', models.BooleanField(default=False)),
                ('is_hiltl', models.BooleanField(default=False)),
                ('is_ladder_user_certified', models.BooleanField(default=False)),
                ('is_scissor_lift_certified', models.BooleanField(default=False)),
                ('is_broom_lift_certified', models.BooleanField(default=False)),
                ('convicted_or_not', models.CharField(default=b'N', max_length=1, choices=[(b'y', b'Yes'), (b'N', b'No')])),
                ('allowed_in_usa', models.CharField(default=b'N', max_length=1, choices=[(b'y', b'Yes'), (b'N', b'No')])),
                ('work_eligible_usa', models.CharField(default=b'N', max_length=1, choices=[(b'y', b'Yes'), (b'N', b'No')])),
                ('domicile_address', models.CharField(default=b'N', max_length=1, choices=[(b'y', b'Yes'), (b'N', b'No')])),
                ('law_suite', models.CharField(default=b'N', max_length=1, choices=[(b'y', b'Yes'), (b'N', b'No')])),
                ('compensation_claim', models.CharField(default=b'N', max_length=1, choices=[(b'y', b'Yes'), (b'N', b'No')])),
                ('other_city', models.CharField(default=b'N', max_length=1, choices=[(b'y', b'Yes'), (b'N', b'No')])),
                ('agreement_signed_date', models.DateField(max_length=100, null=True, verbose_name='Agreement Signed Date')),
                ('driver_license', models.ImageField(null=True, upload_to=b'Upload_documents/')),
                ('signature', models.ImageField(null=True, upload_to=b'Upload_documents/')),
                ('social_security_copy', models.ImageField(null=True, upload_to=b'Upload_documents/')),
                ('certification_copy', models.FileField(null=True, upload_to=b'Upload_documents/')),
                ('resume_copy', models.FileField(null=True, upload_to=b'Upload_documents/')),
                ('comments_area', models.TextField(null=True, verbose_name='Comments', blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='applicationuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='applicationuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='ApplicationUser',
        ),
    ]
